import type { AIPlatform, PromptCategory } from './ai-engine';

export interface PromptTemplate {
  id: string;
  title: string;
  description: string;
  platform: AIPlatform;
  category: PromptCategory;
  templateText: string;
  icon: string;
}

export const promptTemplates: PromptTemplate[] = [
  // ═══════════════ ChatGPT Templates ═══════════════
  {
    id: 'chatgpt-study-1',
    title: 'Exam Preparation Guide',
    description: 'Generate a comprehensive study plan with key topics and practice questions',
    platform: 'chatgpt',
    category: 'study',
    templateText: 'Create a comprehensive exam preparation guide for [subject]. Include key topics, study timeline, practice questions, and memory techniques.',
    icon: 'GraduationCap',
  },
  {
    id: 'chatgpt-study-2',
    title: 'Code Learning Path',
    description: 'Structured learning roadmap for any programming language or framework',
    platform: 'chatgpt',
    category: 'study',
    templateText: 'Design a 30-day learning path for [programming language/framework]. Include daily goals, projects, resources, and milestones.',
    icon: 'BookOpen',
  },
  {
    id: 'chatgpt-content-1',
    title: 'YouTube Script Writer',
    description: 'Create engaging YouTube video scripts with hooks and CTAs',
    platform: 'chatgpt',
    category: 'content',
    templateText: 'Write a YouTube video script about [topic]. Include an attention-grabbing hook, structured sections, and a compelling call-to-action.',
    icon: 'Video',
  },
  {
    id: 'chatgpt-content-2',
    title: 'Instagram Caption Generator',
    description: 'Craft viral Instagram captions with hashtags and engagement hooks',
    platform: 'chatgpt',
    category: 'content',
    templateText: 'Create 5 Instagram captions for [topic/product]. Include emojis, engagement hooks, and relevant hashtags. Tone: [casual/professional/witty].',
    icon: 'Instagram',
  },
  {
    id: 'chatgpt-developer-1',
    title: 'Code Refactoring Assistant',
    description: 'Get suggestions to improve code quality, performance, and readability',
    platform: 'chatgpt',
    category: 'developer',
    templateText: 'Review and refactor the following code for better performance, readability, and best practices: [paste code]. Language: [language].',
    icon: 'Code',
  },
  {
    id: 'chatgpt-business-1',
    title: 'Marketing Campaign Planner',
    description: 'Design a complete multi-channel marketing campaign strategy',
    platform: 'chatgpt',
    category: 'business',
    templateText: 'Create a marketing campaign plan for [product/service]. Include target audience, channels, messaging, budget allocation, and KPIs.',
    icon: 'TrendingUp',
  },
  {
    id: 'chatgpt-creative-1',
    title: 'Short Story Generator',
    description: 'Create compelling short stories with rich characters and plot twists',
    platform: 'chatgpt',
    category: 'creative',
    templateText: 'Write a short story in the [genre] genre about [premise]. Include vivid descriptions, dialogue, and an unexpected plot twist.',
    icon: 'PenTool',
  },

  // ═══════════════ Claude Templates ═══════════════
  {
    id: 'claude-study-1',
    title: 'Research Paper Analysis',
    description: 'Deep analysis of academic papers with structured breakdown',
    platform: 'claude',
    category: 'study',
    templateText: 'Analyze the research paper titled [title]. Provide a structured breakdown of methodology, key findings, limitations, and implications.',
    icon: 'FileSearch',
  },
  {
    id: 'claude-study-2',
    title: 'Concept Explainer',
    description: 'Break down complex concepts with analogies and examples',
    platform: 'claude',
    category: 'study',
    templateText: 'Explain [complex concept] in depth. Use analogies, real-world examples, and build from fundamentals to advanced understanding.',
    icon: 'Lightbulb',
  },
  {
    id: 'claude-content-1',
    title: 'Long-form Blog Post',
    description: 'Write in-depth, well-researched blog articles with SEO optimization',
    platform: 'claude',
    category: 'content',
    templateText: 'Write a comprehensive 2000-word blog post about [topic]. Include an introduction, structured sections, examples, and a conclusion. Optimize for SEO.',
    icon: 'FileText',
  },
  {
    id: 'claude-content-2',
    title: 'Technical Documentation',
    description: 'Create clear, structured technical docs with examples',
    platform: 'claude',
    category: 'content',
    templateText: 'Write technical documentation for [feature/API/library]. Include overview, setup instructions, code examples, and troubleshooting guide.',
    icon: 'Book',
  },
  {
    id: 'claude-developer-1',
    title: 'Architecture Design Document',
    description: 'Design comprehensive system architecture documentation',
    platform: 'claude',
    category: 'developer',
    templateText: 'Create a system architecture document for [project]. Include component diagrams, data flow, technology choices, scalability considerations, and trade-offs.',
    icon: 'GitBranch',
  },
  {
    id: 'claude-business-1',
    title: 'Competitive Analysis Report',
    description: 'In-depth competitive landscape analysis with SWOT framework',
    platform: 'claude',
    category: 'business',
    templateText: 'Conduct a competitive analysis for [company/product] against [competitors]. Include SWOT analysis, market positioning, and strategic recommendations.',
    icon: 'BarChart2',
  },
  {
    id: 'claude-creative-1',
    title: 'World-Building Guide',
    description: 'Create detailed fictional worlds with cultures, history, and lore',
    platform: 'claude',
    category: 'creative',
    templateText: 'Create a detailed world-building guide for a [genre] setting. Include geography, cultures, political systems, magic/technology systems, and key historical events.',
    icon: 'Globe',
  },

  // ═══════════════ Gemini Templates ═══════════════
  {
    id: 'gemini-study-1',
    title: 'Topic Deep Dive',
    description: 'Comprehensive topic exploration with multiple perspectives',
    platform: 'gemini',
    category: 'study',
    templateText: 'Provide a comprehensive deep dive into [topic]. Cover history, current state, key concepts, different perspectives, and future trends.',
    icon: 'Search',
  },
  {
    id: 'gemini-content-1',
    title: 'LinkedIn Post Series',
    description: 'Create a series of professional LinkedIn posts for thought leadership',
    platform: 'gemini',
    category: 'content',
    templateText: 'Create a 5-post LinkedIn series about [topic]. Each post should be engaging, include insights, and build on the previous one. Professional tone.',
    icon: 'Briefcase',
  },
  {
    id: 'gemini-developer-1',
    title: 'Code Review Checklist',
    description: 'Generate a thorough code review checklist for your project',
    platform: 'gemini',
    category: 'developer',
    templateText: 'Create a comprehensive code review checklist for a [language/framework] project. Include security, performance, readability, and testing criteria.',
    icon: 'CheckSquare',
  },
  {
    id: 'gemini-business-1',
    title: 'Market Research Summary',
    description: 'Quick market research synthesis with actionable insights',
    platform: 'gemini',
    category: 'business',
    templateText: 'Summarize the market landscape for [industry/niche]. Include market size, trends, key players, opportunities, and potential risks.',
    icon: 'PieChart',
  },
  {
    id: 'gemini-business-2',
    title: 'SEO Content Strategy',
    description: 'Develop a keyword-focused content strategy plan',
    platform: 'gemini',
    category: 'business',
    templateText: 'Create an SEO content strategy for [website/business]. Include keyword research, content calendar, topic clusters, and optimization tactics.',
    icon: 'Target',
  },
  {
    id: 'gemini-creative-1',
    title: 'Art Prompt Collection',
    description: 'Generate creative art prompts for various AI image generators',
    platform: 'gemini',
    category: 'creative',
    templateText: 'Generate 10 creative art prompts for [style/theme]. Each should describe subject, style, lighting, mood, and composition in detail.',
    icon: 'Palette',
  },

  // ═══════════════ Perplexity Templates ═══════════════
  {
    id: 'perplexity-study-1',
    title: 'Research Paper Finder',
    description: 'Find and summarize relevant academic papers on any topic',
    platform: 'perplexity',
    category: 'study',
    templateText: 'Find the most cited research papers on [topic] from the last 5 years. Summarize key findings and provide source links.',
    icon: 'Search',
  },
  {
    id: 'perplexity-content-1',
    title: 'Trending Topic Analyzer',
    description: 'Analyze current trends and create content angles',
    platform: 'perplexity',
    category: 'content',
    templateText: 'Analyze current trends around [topic]. What are people searching for? What content gaps exist? Provide data-backed content angles.',
    icon: 'TrendingUp',
  },
  {
    id: 'perplexity-developer-1',
    title: 'Technology Comparison',
    description: 'Compare technologies with real benchmarks and community feedback',
    platform: 'perplexity',
    category: 'developer',
    templateText: 'Compare [tech A] vs [tech B] for [use case]. Include performance benchmarks, community size, learning curve, and real-world case studies.',
    icon: 'Scale',
  },
  {
    id: 'perplexity-business-1',
    title: 'Industry Report Generator',
    description: 'Generate a data-driven industry analysis report',
    platform: 'perplexity',
    category: 'business',
    templateText: 'Create an industry report for [industry] covering market size, growth rate, key players, emerging trends, and investment opportunities. Cite sources.',
    icon: 'FileBarChart',
  },
  {
    id: 'perplexity-creative-1',
    title: 'Cultural Research Brief',
    description: 'Research cultural trends and movements for creative projects',
    platform: 'perplexity',
    category: 'creative',
    templateText: 'Research current cultural trends in [area/genre]. What movements are emerging? What visual styles are popular? Provide examples and sources.',
    icon: 'Compass',
  },

  // ═══════════════ Sora Templates ═══════════════
  {
    id: 'sora-creative-1',
    title: 'Cinematic Scene Generator',
    description: 'Create detailed cinematic scene descriptions for AI video generation',
    platform: 'sora',
    category: 'creative',
    templateText: 'Create a cinematic scene: [scene description]. Include camera movement, lighting, color palette, atmospheric details, and character actions.',
    icon: 'Film',
  },
  {
    id: 'sora-creative-2',
    title: 'Product Commercial',
    description: 'Design a visually stunning product advertisement video prompt',
    platform: 'sora',
    category: 'creative',
    templateText: 'Design a 30-second product commercial for [product]. Include scene transitions, product showcase moments, lighting style, and mood.',
    icon: 'ShoppingBag',
  },
  {
    id: 'sora-content-1',
    title: 'Music Video Concept',
    description: 'Create a visual concept for a music video with scene breakdowns',
    platform: 'sora',
    category: 'content',
    templateText: 'Design a music video concept for a [genre] song about [theme]. Include scene descriptions, visual transitions, color grading, and symbolic imagery.',
    icon: 'Music',
  },
  {
    id: 'sora-content-2',
    title: 'YouTube Intro Animation',
    description: 'Design an eye-catching YouTube channel intro animation',
    platform: 'sora',
    category: 'content',
    templateText: 'Create a 5-second YouTube intro animation for a [niche] channel. Include motion graphics style, color scheme, text animation, and energy level.',
    icon: 'Play',
  },
  {
    id: 'sora-business-1',
    title: 'Brand Story Video',
    description: 'Create a compelling brand story video concept',
    platform: 'sora',
    category: 'business',
    templateText: 'Design a brand story video for [company/brand]. Include narrative arc, visual metaphors, emotional beats, and brand color integration.',
    icon: 'Award',
  },

  // ═══════════════ Copilot Templates ═══════════════
  {
    id: 'copilot-developer-1',
    title: 'API Endpoint Generator',
    description: 'Generate complete REST API endpoints with validation and error handling',
    platform: 'copilot',
    category: 'developer',
    templateText: 'Create a REST API endpoint for [resource] in [framework]. Include CRUD operations, input validation, error handling, and TypeScript types.',
    icon: 'Server',
  },
  {
    id: 'copilot-developer-2',
    title: 'Unit Test Suite',
    description: 'Generate comprehensive unit tests for your code',
    platform: 'copilot',
    category: 'developer',
    templateText: 'Write a comprehensive unit test suite for [function/class] in [language]. Include edge cases, error scenarios, mocking, and assertions.',
    icon: 'TestTube',
  },
  {
    id: 'copilot-developer-3',
    title: 'Database Schema Designer',
    description: 'Design optimized database schemas with relationships',
    platform: 'copilot',
    category: 'developer',
    templateText: 'Design a database schema for [application type]. Include tables, relationships, indexes, and migrations in [SQL/ORM]. Consider scalability.',
    icon: 'Database',
  },
  {
    id: 'copilot-study-1',
    title: 'Algorithm Explainer',
    description: 'Understand algorithms with step-by-step code walkthrough',
    platform: 'copilot',
    category: 'study',
    templateText: 'Explain the [algorithm name] algorithm with a step-by-step code implementation in [language]. Include time/space complexity and use cases.',
    icon: 'Binary',
  },
  {
    id: 'copilot-content-1',
    title: 'README Generator',
    description: 'Create professional README files for GitHub repositories',
    platform: 'copilot',
    category: 'content',
    templateText: 'Generate a professional README.md for [project name]. Include description, features, installation, usage, API docs, and contributing guidelines.',
    icon: 'FileText',
  },
  {
    id: 'copilot-business-1',
    title: 'Tech Stack Evaluator',
    description: 'Evaluate and recommend technology stacks for business needs',
    platform: 'copilot',
    category: 'business',
    templateText: 'Evaluate the best tech stack for [project type]. Compare options for frontend, backend, database, and deployment. Consider team size: [size], budget: [budget].',
    icon: 'Layers',
  },
];
